### ISSUE TITLE
Documentando unidad-0-asignacion-3-mi-primer-rmd

### ISSUE THREAD

**Issue by geofis** [biogeografia-201902/unidad-0-asignacion-3-mi-primer-rmd-hoyodepelempito#1]
@biogeografia-201902/estudiantes, aquí les dejo, en capturas de pantalla, los pasos dados por @hoyodepelempito.

Sólo un detalle por el que quizá a algunos/as les fallaba: verificar que la línea 10 (podría caer en la 12) del `.Rmd` pone `eval=T`. De lo contrario, cámbienla en su repo local de RStudio.

**En el servidor RStudio habilitado por el profesor, o en el RStudio Desktop de sus PC:**

---
*Crear proyecto*
![00](https://user-images.githubusercontent.com/13460617/64531702-19447400-d2de-11e9-9ea0-746382dd50c0.png)

---
![01](https://user-images.githubusercontent.com/13460617/64531590-e5694e80-d2dd-11e9-94b8-25ee72842f97.png)

---
*Configurar usuario local*
![02](https://user-images.githubusercontent.com/13460617/64531734-295c5380-d2de-11e9-8db6-a8b474bee392.png)
![03](https://user-images.githubusercontent.com/13460617/64531855-5ad51f00-d2de-11e9-9fbb-f55d01e7cb5a.png)

---
*Abrir archivo `README.Rmd`*
![03b](https://user-images.githubusercontent.com/13460617/64531889-67f20e00-d2de-11e9-98cd-741ab2f2d48c.png)

---
*Verificar que línea 10 (podría caer en la 12) ponga `eval=T`*
![03c](https://user-images.githubusercontent.com/53181265/64534513-96beb300-d2e3-11e9-8b14-3ca3d1829042.png)

---
*Tomar nota del número asignado*
![04](https://user-images.githubusercontent.com/13460617/64531943-82c48280-d2de-11e9-90f2-288d2c29a7ee.png)

---
*Configurar RStudio para que haga que los bloques de código de RMarkdown se ejecuten en la consola*
![05](https://user-images.githubusercontent.com/13460617/64531952-8821cd00-d2de-11e9-9b3f-a8e5ec670948.png)

---
*Escribir lo que se me pide en la tarea 1 (este tutorial sólo incluye Tarea 1, las otras deben realizarlas*
![06](https://user-images.githubusercontent.com/13460617/64531962-8ce68100-d2de-11e9-95dc-5e4bd6ab6c56.png)

---
*Seleccionar una línea para ejecutar (o colocar el cursor sobre ella)*
![07](https://user-images.githubusercontent.com/13460617/64531972-9243cb80-d2de-11e9-9a6e-02f95b7bafcf.png)

---
*Presionar `Run Selected Line(s)`*
![08](https://user-images.githubusercontent.com/13460617/64531982-996ad980-d2de-11e9-9773-072102590c53.png)

---
*Verificar resultado en la consola de R*
![09](https://user-images.githubusercontent.com/13460617/64532477-97554a80-d2df-11e9-9b84-cc0d2c782a98.png)

---
*Hacer lo mismo con las demás líneas de la Tarea 1*
![11](https://user-images.githubusercontent.com/13460617/64532560-b2c05580-d2df-11e9-9436-c40d753c268a.png)
![12](https://user-images.githubusercontent.com/13460617/64532665-f0bd7980-d2df-11e9-831b-cec0cff9e224.png)

---
*Tejer*
![13](https://user-images.githubusercontent.com/13460617/64532685-fc10a500-d2df-11e9-9dc1-17a7cd93ad11.png)

---
*Podría aparecer un mensaje de ventanas emergentes bloqueadas (dependerá de la configuración del navegador)*
![14](https://user-images.githubusercontent.com/53181265/64533631-e4d2b700-d2e1-11e9-8255-50bb878f585f.png)

---
*Habilitar las ventanas emergentes para el sitio*
![15](https://user-images.githubusercontent.com/53181265/64533642-ec925b80-d2e1-11e9-9b5b-0fc593a5d622.png)

---
*Intentar de nuevo*
![16](https://user-images.githubusercontent.com/53181265/64533655-f4520000-d2e1-11e9-8876-846b41620164.png)

---
*Con suerte, te saldrá una ventana emergente con los resultados tejidos en Markdown*
![17](https://user-images.githubusercontent.com/13460617/64532869-51e54d00-d2e0-11e9-924e-47bc6b61c4f7.png)

---
*Commit*
![18](https://user-images.githubusercontent.com/13460617/64532900-6590b380-d2e0-11e9-8df5-14c4edd349c1.png)
![19](https://user-images.githubusercontent.com/13460617/64532901-6590b380-d2e0-11e9-85d9-779dfa2d587b.png)
![20](https://user-images.githubusercontent.com/13460617/64532902-6590b380-d2e0-11e9-9678-90792b34bcd7.png)

---
*Push*
![21](https://user-images.githubusercontent.com/13460617/64532918-70e3df00-d2e0-11e9-8b39-3f8c79ff5ac0.png)
![22](https://user-images.githubusercontent.com/13460617/64532948-7e996480-d2e0-11e9-9f82-a875a246ade9.png)

**En el GitHub:**
---
*Verifica el resultado en el GitHub*
![23](https://user-images.githubusercontent.com/13460617/64532966-89ec9000-d2e0-11e9-9f16-566d24102ef9.png)

**Completar las demás tareas de la asignación usando el número asignado**

**Comment by dahianagb07** [comment]
Funcionó!

**Comment by geofis** [comment]
Confirmado:

![Selección_006](https://user-images.githubusercontent.com/13460617/64551457-10b26480-d303-11e9-9491-85deb079de5c.png)

¡Aplauso! 
@biogeografia-201902/estudiantes

**Comment by geofis** [comment]
@biogeografia-201902/estudiantes. Nuevos aplausos: @JuanJoseGH06, @emdilone, @BidelkisCastillo y @maritzafg. También @Jorge-Mutonen @yanderlin hicieron esta práctica, pero todavía tienen algunas cuestiones que corregir.
